spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:oracle:thin:@192.168.51.50:1521/HIPDB
    url: jdbc:mysql://47.98.143.181:3306/salemarket?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: HIP_SALE
#    password: hip000
    username: root
    password: 1Q2W3E4R
    max-idle: 10
    max-wait: 10000
  freemarker:
      cache: false
      template-loader-path: classpath:/templates/
jfw:
  is-dev: true
  dev-server-port: 8000
  is-ldap: false
  is-user-ldap: false
  is-inform: true
  is-add-user: true
  open-platom-url: http://192.168.51.82:8002

ldap:
  host: 192.168.1.82
  port: 389
  binddn: cn=admin,dc=joinforwin,dc=com
  password: 1qaz
  userPosition: ou=people,dc=joinforwin,dc=com
  match:
    telephoneNumber: MOBILE_PHONE
    userPassword: PASSWORD
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.joinforwin.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
